- name: Monit APT key
  apt_key:
    id: 7B1A50D3B5A35322FFE0BC2BDAFCF825D62EB07F
    keyserver: hkp://keyserver.ubuntu.com:80
- name: Monit APT repository
  apt_repository:
    repo: deb http://ppa.launchpad.net/molindo/ppa/ubuntu trusty main
    state: present
    update_cache: yes
- name: Monit configuration directory
  file:
    state: directory
    dest: /etc/monit/conf.d/
- name: Monit configuration
  template:
    src: monitrc.j2
    dest: /etc/monit/monitrc
  notify: restart monit
- name: Monit checks
  copy:
    src: "{{ monit_checks_file }}"
    dest: /etc/monit/conf.d/{{ monit_checks_file | basename }}
  notify: restart monit
- name: Install Monit
  apt:
    name: monit=1:5.15-1~ubuntu14.04.1~ppa1
    state: present
